language: cpp
compiler: 
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt-sdk libgcrypt11-dev zlib1g-dev
script: cmake . && make && ctest
branches:
  only:
    - master
